name: First Workflow

on: push                # whenever anything pushed to this repo this workflow will get executed
#on: [push, fork]       # we can also mention multiple events

jobs:
    first_job:
        runs-on: ubuntu-latest      # where this job to run
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List and Read file
          run: |
            echo "My first Github Workflow"
            ls -lrt
            cat README.md

        - name: Generate ASCII 
          run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt  # cowsay is 3rd party library for generating ascii

        # - name: Welcome Message
        #   run: |
        #     echo "My first Github Workflow"      # what to run in the machine
        
        # - name: List files
        #   run: ls

        # - name: Read file
        #   run: cat README.md
